### ISSUE TITLE
Japanese garbled 

### ISSUE THREAD

**Issue by EbXpJ6bp** [warrenbuckley/IIS-Express-Code#10]
Hi, great plugin.

Variable-width encoding is very unique. Chinese language requires gbk, but Japanese language requires Shift_JIS. Is it possible to support them?

I thank you for reading it through.

**Comment by warrenbuckley** [comment]
Hello @EbXpJ6bp this would have to be done as a Pull Request, as I have no easy way to test & verify this change.

Is this something your happy to do a PR to this project?

Thanks,
Warren :)
