### ISSUE TITLE
Restart IIS

### ISSUE THREAD

**Issue by clausjensen** [warrenbuckley/IIS-Express-Code#14]
It seems like whenever the IIS instance completely crashes (for example with a stackoverflow exception) the plugin doesn't really know about it. So to restart the site you have to issue a `stop` and then a `start` command to actually have it start up the instance again.

Could be great to have a `restart` option that was able to do this in just one step ... or maybe even just have the `start` command do a restart (stop+start) if it thinks the server is already running when you choose `start`.

**Comment by warrenbuckley** [comment]
Hey @clausjensen 
Also managed to get this done today in FF in v 0.0.6

The restart option does exactly as you suggest of doing a `stop` followed by a `start`
