### ISSUE TITLE
Option for creating the .vscode settings file with port

### ISSUE THREAD

**Issue by clausjensen** [warrenbuckley/IIS-Express-Code#15]
Having a command to initialize the settings file so you won't have to manually create it (or copy and modify one from an existing site) could be awesome.

Being able to select `Initialize config file` as a command and then input a port number would be even more awesome 😄

**Comment by warrenbuckley** [comment]
Hey @clausjensen 
Managed to get this done today in FF with version 0.0.6

The file gets created automatically & some JSON Schema is applied to the file too, so you know what is the valid properties & settings. Such as not allowing a port number less than 1024.
