### ISSUE TITLE
Command for Launch

### ISSUE THREAD

**Issue by daughtkom** [warrenbuckley/IIS-Express-Code#16]
Consider a new command to launch an already running site (for example, if I closed the browser and don't remember the port).  Or maybe change the Start command to simply launch if IIS is already started.

I know I can use the output window, but this would be faster.

Thanks,

**Comment by warrenbuckley** [comment]
No definitely a good idea @daughtkom the amount of times I must admit I do the same & forget, hope to get some free time soon to work on some of these issues & this will be included.

**Comment by warrenbuckley** [comment]
Hi @daughtkom 
This has been done with the latest release in v0.0.6 where clicking the name of the site url in the status bar at the bottom of the VS Code window will re-open your browser with the URL.
