### ISSUE TITLE
can i customsize run port?

### ISSUE THREAD

**Issue by nebulax2014** [warrenbuckley/IIS-Express-Code#2]
hi, I use iis express in vs code , it is run on random port everytime , but  I want to customize the run  port as 8080, can i do it?

**Comment by warrenbuckley** [comment]
Hi @nebulax2014 not currently would need to think of a best way to do this.

**Comment by nebulax2014** [comment]
ok, thanks.

**Comment by xrkolovos** [comment]
We could have an iisexpress.json file inside .vscode folder with some settings 
like this one 
https://github.com/Microsoft/vscode-samples/blob/master/node-express-javascript/.vscode/launch.json

**Comment by mogulman52** [comment]
This feature seems to be added in 0.0.3.  Is there an example iisexpress.json file I can refer to?  Thanks.

**Comment by warrenbuckley** [comment]
You need the following file added `.vscode/iisexpress.json`

```
{
    "port":8081
}
```
