### ISSUE TITLE
Error running extension

### ISSUE THREAD

**Issue by szul** [warrenbuckley/IIS-Express-Code#20]
When attempting to start IIS, the following error occurs:

"Running the contributed command:'extension.iis-express.start' failed."

No other information is provided. Is there a way to produce a log dump? IIS is installed, and I have been able to run it from the command line.

**Comment by warrenbuckley** [comment]
What version of VS Code are you running?
What version of the extension are you running?
And finally what OS version along with 32 or 64bit?

**Comment by szul** [comment]
VSCode: 1.8.1
extension: 0.0.6
Windows 10 64-bit

**Comment by VALIKCOOL** [comment]
Setup same as above
getting the same error

**Comment by warrenbuckley** [comment]
Have either of you cloned the source of this repo @szul & @VALIKCOOL to debug & find where the error is being caused?

Do you have IISExpress installed and if so at what path is it installed at?

**Comment by SiOuz** [comment]
Same error
VSCode: 1.8.1
extension: 0.0.6
Windows 10 64-bit
IIs Express Amd_64,

i have to add myself the file iisexpress
with the follow content 
{
    "port":8081
}
But i have HTTP Error 403.14 - Forbidden after that

**Comment by warrenbuckley** [comment]
Is the folder got any read/write permissions if the IIS express config file is not being written automatically for you @SiOuz ?

Additionally do you have an start page of some sort in the folder, such as index.html, index.asp etc...?!

**Comment by szul** [comment]
This started working again on my home computer. Will check my work computer to verify. If it works there, it might be safe to close this issue. @VALIKCOOL @SiOuz either of you still experiencing this?

**Comment by TylerCode** [comment]
The issue seems to still be relevant in [this question over at stack exchange](http://stackoverflow.com/questions/43055889/using-php-and-mysql-in-vs-code/43056013?noredirect=1#comment73325383_43056013). I've sort of run out of ideas for him.

**Comment by rajeshwarkohli** [comment]
I am having the same issue. When running the PHP file by placing in the directory C:\inetpub\wwwroot works by entering localhost/test.php (test is the file name) in browser. But on opening folder in VSCode and running via extension I get same error. Seems extesnsion needs to be linked with IIS Express in my case. IIS Express is placed in default directory i.e. C:\Program Files\IIS Express and I am running Windows 10, IIS Express 10, Vscode 1.10.2 and no log files are being created in IIS Express folder placed in Documents and I don't see any IISExpress.json file in my folder where I am working.

**Comment by warrenbuckley** [comment]
Can you please try a different folder where you perhaps have full file permissions to create files. Can you try a simple folder say on the desktop with a simple index.html file in it and see if it works for you there @rajeshwarkohli

**Comment by rajeshwarkohli** [comment]
Still does not work. I was using folder placed in documents before. Actually C:\inetpub\wwwroot is the localhost root directory and I had just tried there just to see if it works.

**Comment by warrenbuckley** [comment]
@rajeshwarkohli OK this is hard for me to debug without your machine here with me.

You have mentioned before that you cannot see the file so I am wondering if it does not exist.

Can you create a file like so in the folder containing the test index.html on your desktop.
* Create new folder called `.vscode`
* Create a new file called `iisexpress.json` inside `.vscode`
* Use the following contents - obviously change the path to your folder on your desktop

```
{
  "port": 11026,
  "path": "c:\\Code\\example-folder",
  "clr": "v4.0"
}
```

**Comment by rajeshwarkohli** [comment]
@warrenbuckley Now the extension is working but only running index.html even if running any other file. And after some research, I disabled default file in IISExpress and enabled directory browsing  but still same problem.

**Comment by warrenbuckley** [comment]
Where did you change these settings @rajeshwarkohli in a web.config inside the folder with index.html or IISExpress config found at `%HOMEPATH%/documents/IISExpress/config`

If the index.html file ran then I would say the extension is working - but sounds like something may be misconfigured in what you are trying to do.

The extension does not currently support running PHP sites - due to the way IISExpress is invoked from the command line - but I have a task to add support for this in the future #6

**Comment by rajeshwarkohli** [comment]
@warrenbuckley I changed the settings in IIS Manager. I don't know the way to do as you mentioned.

I am trying to solve problem for a long time but facing a new issue after one or another. And I am trying to run basic .php file. Could you solve it for me by using TeamViewer.

**Comment by abhiranjankumar00** [comment]
I'm also facing the same problem for quite a while. Temporarily fixed it by creating a task.

**Comment by abhiranjankumar00** [comment]
The last major blocker for an F# developer, debugger for F# (https://github.com/ionide/ionide-vscode-fsharp/pull/344), is being removed and VsCode can be used from end to end development of a project.

**Comment by szul** [comment]
Since my issue has resolved itself, and other comments seem to be a different issue (php), I'm going to close this out.

**Comment by roryzoerb** [comment]
Updated VSCode this morning to Version 1.12. Opened first project of the day (html) and experienced the same problem. Tried IIS-Express-Code uninstall, full reboot and IIS-Express-Code reinstall - no joy. Created iisexpress.json file in .vscode and I'm back work.

**Comment by warrenbuckley** [comment]
I know the cause of this problem now and should be fixed in an upcoming release.
The problem was to do with users having pre-existing `.vscode` folders already

**Comment by roryzoerb** [comment]
Just installed the new release, created a new project with a .vscode and it works flawlessly again - 5 stars

**Comment by warrenbuckley** [comment]
Ace great to hear @roryzoerb - make sure to give that 5 stars on the listing page on the marketplace :)

**Comment by roryzoerb** [comment]
Works great! Thank you!!
