### ISSUE TITLE
Add ability to use VSCode vars in settings

### ISSUE THREAD

**Issue by ghost** [warrenbuckley/IIS-Express-Code#22]
I want to use a relative path for the "path" settings because I need to start the IIS with a sibling path of my workspace.
In the tasks.json I could do something like: "${workspaceRoot}...\myFolder" 
It would be nice to have this feature also in this plugin.

**Comment by warrenbuckley** [comment]
Yes I agree this is a good idea & I currently do not have time to look at this right now, but I would ❤️ to get this done and pulled in.

If you feel comfortable or happy to do so, a PR for this would be fantastic.

**Comment by warrenbuckley** [comment]
So the only two that make sense to me to use are `${workspaceRoot}` or `${workspaceRootFolderName}` but it looks like this is not currently possible for extension authors as of yet - https://github.com/Microsoft/vscode/issues/2809

**Comment by warrenbuckley** [comment]
Closing as duplicate for relative path issue #25
