### ISSUE TITLE
add relevant priveiw in detales

### ISSUE THREAD

**Issue by perXautomatik** [warrenbuckley/IIS-Express-Code#234]
like the thought of this plugin but won't try it due to it not having a setup scenario in the detales page.

i know such a well endorsed plugin creator don't need my support and should for that reason not do any changes because me a privileged snowflake demands it, but rather due to me thinking that many more would be drawn to the plugin if instead of a looping installation gif (which according to me is superfluous) would be replaced with a setup scenario and example page render.

wish you best of luck otherwise

**Comment by warrenbuckley** [comment]
Thanks for your feedback @perXautomatik 
I will close this issue for now as I think the readme covers how to use the extension.
