### ISSUE TITLE
Relative path

### ISSUE THREAD

**Issue by ZeBobo5** [warrenbuckley/IIS-Express-Code#25]
Is it able to use relative paths in iisexpress.json ?

Thanks

**Comment by warrenbuckley** [comment]
Hi @ZeBobo5 I think this may be related to this task?
https://github.com/warrenbuckley/IIS-Express-Code/issues/22

**Comment by warrenbuckley** [comment]
Can you give me an example of a relative path you would like to try to use. Is it a folder outside what you have open in VSCode @ZeBobo5 ?

**Comment by warrenbuckley** [comment]
Hi @ZeBobo5 is there more details about this what you want to achieve, otherwise I will close this issue?

**Comment by ab18556** [comment]
To be able to set a relative path ( or to use vscode vars) is mandatory when you have multiple devs working on the same project.
