### ISSUE TITLE
Add Start, Restart & Stop to Menu

### ISSUE THREAD

**Issue by warrenbuckley** [warrenbuckley/IIS-Express-Code#26]
Use VSCode Contribution Point to add Menu Items
http://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesmenus

**Comment by Seefer** [comment]
Just installed this and I get errors when trying to Start Website from VS Code command palette. as below. Is this a related issue?

**Running the contributed command:'extension.iis-express.start' failed.**

**Comment by warrenbuckley** [comment]
The issue I created is for adding menu options based on VSCode extension points. 

It seems like you have ran into a bug/problem where iis express cannot start in the extension. 

Can you detail me some errors please such as version of OS, VSCode, path to iisexpresss.exe 

So I can try to reproduce the problem.

**Comment by Seefer** [comment]
VS Code is version = **1.11.2**
IIS Express version according to .exe file Properties = **10.0.14358.1000.**
Currently running Windows 10 Insider Preview OS Build **15063.138**.

The path to iisexpress.exe on my system is **C:\Program Files\IIS Express** and this is present in the **Path** variable in system environment variables.

**Comment by warrenbuckley** [comment]
@Seefer OK thanks for the version details. The folder you are trying to run as a site, do you have folder permissions to create files in there?

As when trying to run the extension it should try to attempt to write its configuration file to `.vscode/iisexpress.json`

If this files does not exist can you create it manually. It's a JSON file and you should get intellisense/autocompletion for the available properties/settings.

**Comment by Seefer** [comment]
Hey Warren.

Manually adding `iisxpress.json` file to the .vscode folder and using Intellisense to populate it with the `clr `and `port `properties did the trick and things work beautifully so far.

I do not think I have permissions issues. The projects I create are on my D: drive in 01-Projects. I’ve had no issues of this nature with json files such as `launch.json` and `settings.json` being automatically created in .vscode. I’m new to this editor maybe there’s a configuration setting I’m unaware of?

**Comment by warrenbuckley** [comment]
Interesting that by adding the file manually it worked so it seems to fail by automatically creating it. 

Are you able to reproduce the problem in a new folder that you wish to run/open in IIS?

If so if you feel comfortable cloning the source and attaching the debugger in the code to see why you get the error.

**Comment by Seefer** [comment]
Decided to delete and recreate project folder on my D drive and everything works fine. Permissions issues may have indeed been a problem but not sure how they arose? I've been working in that folder with Visual Studio 2017 for quite some time with no issues :)

**Comment by warrenbuckley** [comment]
@Seefer I know the cause of your problem and managed to solve this error you was having that is fixed in an upcoming 1.0.0 release.

I suspect you had a pre-existing `.vscode` folder already which the extension was trying to create for you when it could not find the iisexpress.json file
