### ISSUE TITLE
IISExpress.exe file location issues

### ISSUE THREAD

**Issue by bnjmnmyers** [warrenbuckley/IIS-Express-Code#30]
When I try to run start command I get a message saying that it can't find IIS Express in C:\Program Files. My copy is being run out of C:\Program Files (86x). How do I change where the extension is looking for IIS Express?

**Comment by schwarzie2478** [comment]
I too found it strange that this doesn't work, but it used to work...
Then I remember that I am now running the 64bit version of VS Code.

I see in the code that the environment variable ProgramFiles which points  to the undesired folder when running VS Code 64bit.

You could install the 32bit version for VS Code

**Comment by schwarzie2478** [comment]
Just confirmed it my machine,  the 32bit version of VS Code works. 
I downloaded a zipped version of that one so I don't have to install it again. 

But a configurable option would be nice.

**Comment by warrenbuckley** [comment]
Thanks for this. I have been on a long weekend and will look later tonight or tomorrow and see if I can get a fix out. 

I may be back later for more questions and testing :)

**Comment by warrenbuckley** [comment]
@bnjmnmyers @schwarzie2478 Are either of you still having this problem that I need to investigate this or is it resolved and that I can close this issue?

**Comment by warrenbuckley** [comment]
Closing this issue as you can sepcify/override the location of IISExpress & AppCmd.exe via configuration with this PR #86
