### ISSUE TITLE
Strange Words in OUTPUT Panel

### ISSUE THREAD

**Issue by MarkSky** [warrenbuckley/IIS-Express-Code#32]
In OUTPUT panel, there are many strange words, so I don't know what does it mean.
![-1](https://user-images.githubusercontent.com/4032734/32534766-f9c5892c-c491-11e7-916d-af0b24016568.jpg)

**Comment by warrenbuckley** [comment]
Hi @MarkSky this may be some encoding issue.
What is your locale of your machine?

As another user helped out with Chinese output with a commit a while back that helped them
https://github.com/warrenbuckley/IIS-Express-Code/commit/5bdda4f4988d66590d10e620f1debb2287c3dd7a#diff-9f7b85adaaa3a8713da2f88a7d52e437

If you can give me some more details I will try my best to help out here

**Comment by MarkSky** [comment]
My WIndows is Traditional Chinese.
My VS Code locale has setted to "zh-TW" or "en-US", but there is the same error in these two setting.

**Comment by warrenbuckley** [comment]
Hi @MarkSky I am not sure how to reproduce or debug this error.
What I can recommend is cloning this project down & stepping through the code with a breakpoint setup so you have a local copy of the IIS Express extension for VS Code.

I would imagine that method I linked to in the commit from another community member is not covering all scenarios with Chinese character set.

**Comment by warrenbuckley** [comment]
@MarkSky is this still an issue for you? If it is please re-open this issue

**Comment by MarkSky** [comment]
I still have the same error after updated to 1.1.0

I don't know if it depends on VSCode encoding?

**Comment by warrenbuckley** [comment]
@MarkSky Yeh I am not entirely sure to be honest & how to reproduce this, as I dont have access to a machine/VM to reproduce this.

I will need your help/input on this one & try to clone the repo down & contribute back if you feel comfortable to do so.

**Comment by MarkSky** [comment]
I have try to use the developer tool, and get some information:
![vscode1](https://user-images.githubusercontent.com/4032734/37331188-39d51cf4-26de-11e8-8c56-fdcc8666a16d.jpg)
![vscode2](https://user-images.githubusercontent.com/4032734/37331208-457799ec-26de-11e8-833f-c94ae8e72a98.jpg)
Do you mean this?

**Comment by warrenbuckley** [comment]
Hi @MarkSky 
Not quite - you will need to do the following:

- Git clone this repo
- Open folder in VS Code
- From a terminal at the root of the project do `npm install`
- VS Code down the left hand side has the debug/bug symbol
- From the dropdown next to the start debugging green play icon should be something like `Launch VS Code Extension` or similarly worded
- You should be able to set breakpoints in the source code & test out your changes
