### ISSUE TITLE
Starting a server does not work prompts error "ERROR: spawn TRY_INSTALL_IIS ENOENT"

### ISSUE THREAD

**Issue by ghost** [warrenbuckley/IIS-Express-Code#360]
Starting a server prompts error "ERROR: spawn TRY_INSTALL_IIS ENOENT"
Repro steps:
- Install extension
- Open command palette and select IIS Express: Start website

Browser opens but page does not load, log says "ERROR: spawn TRY_INSTALL_IIS ENOENT", and trying to start again says "IIS Express is already running"

**Comment by warrenbuckley** [comment]
Hi @tccimpact 
Can you tell me more about your machine and setup please.

What version of Windows?
What version of VSCode
Can you use IIS Express from Visual Studio or JetBrains Rider ?

**Comment by ghost** [comment]
Sure, it's

Windows 10 x64 build 19042.928
VS Code version 1.56.0

I tried uninstalling the extension and installing again, I also tried opening VS Code as admin, installing, running, all to the same error.
Not sure what else to try

**Comment by warrenbuckley** [comment]
Have you used IIS Express as part of big brother Visual Studio at all @tccimpact and does that work all OK for you @tccimpact

**Comment by danjdewhurst** [comment]
I got past this error by installing IIS Express manually.

**Comment by warrenbuckley** [comment]
@tccimpact Did you not have IIS Express installed already. I know my extension tries to download and install it for you and not always super easy to test this workflow out, but I may need to revisit it.

**Comment by ghost** [comment]
I did not have Visual Studio nor IIS Express installed. Now that I do have it, the extension seems to be working fine, so idk it could be specific to my machine and permissions.
Perhaps if it's a common problem there could be a "Common issues" session in the README suggesting manual install as a workaround?
