### ISSUE TITLE
use launchSettings.json?

### ISSUE THREAD

**Issue by robertppn** [warrenbuckley/IIS-Express-Code#38]
Hi!
Is there a way to let the extension use the launchSettings.json file for startup parameters?

thx

**Comment by warrenbuckley** [comment]
Hi @robertppn 
Is launchSettings.json something that comes from a typical .NET Core WebApplication?

I have yet to do much work with .NET Core. What does the file contain & how is it normally used?

**Comment by robertppn** [comment]
Hi,
Well I'm no expert and I don't know if its specific for .Net core but its a Visual Studio file:

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments#development

And it's used for debugging/starting a web application in Visual studio.

**Comment by warrenbuckley** [comment]
Hi @robertppn 
Looking at this file I am not entirely sure there is anything specific in this file that I can use from it.

If you know how IIS Express can use it or consume it from the command line then I will happily try to implement it, otherwise I will close this issue.

Thanks,
Warren

**Comment by robertppn** [comment]
u could grab these settings from the file just as u parse the iisexpress.json file right?

  "iisSettings": {
    "windowsAuthentication": true,
    "anonymousAuthentication": false,
    "iisExpress": {
      "applicationUrl": "http://localhost:9180/",
      "sslPort": 0
    }
  }

**Comment by warrenbuckley** [comment]
@robertppn I will have to do some investigation on how the full VS IDE uses & invokes IIS Express with these settings. This may take me a while to investigate & find out whats going on.

**Comment by Elrinth** [comment]
I wanna have the iis express start on:
<binding protocol="http" bindingInformation="*:8689:*" />
instead of
<binding protocol="http" bindingInformation="*:8689:localhost" />

**Comment by sjetha-pason** [comment]
It's the applicationhost.config file that we need to target when trying to run an ASP.NET Core application.
Currently, this extension only looks for command-line parameters such as the path and the port, but doesn't allow for the settings file to contain a link to a config file, which is how Visual Studio gets things going.

There are a few elements besides this that need to be set up for it to work as intended form VSCode, I found this blog post that would help give direction to this: https://blog.lextudio.com/how-visual-studio-launches-iis-express-to-debug-asp-net-core-apps-d7fd3677e3c3

**Comment by warrenbuckley** [comment]
Thanks @sjetha-pason for the link, I will read it and investigate, otherwise feel free to submit a PR if you know what is exactly needed for this to be supported.

**Comment by loligans** [comment]
This could be a really cool feature.

**Comment by warrenbuckley** [comment]
.NET Core from VS uses an applicationhost.config file found at .vs folder at root of project
![image](https://user-images.githubusercontent.com/1389894/86542090-2afca500-bf0a-11ea-91b3-8ee14f094cb4.png)

**Comment by warrenbuckley** [comment]
Closing this issue as a duplicate as this will be solved by #33 and the community PR #36
