### ISSUE TITLE
Specify a subfolder to launch IIS Express from.

### ISSUE THREAD

**Issue by JoveFx** [warrenbuckley/IIS-Express-Code#4]
Hi, great plugin, I wanted to ask if it would be possible to make another enhancement of it.

Id like to have the option to specify which sub-folder -within the the main project folder,  that IIS Express begins to serve pages from. Many projects have a large amount of outputs, and being able to specify sub-folders would be awesome.

Either way, thanks for the plugin!

**Comment by warrenbuckley** [comment]
@JoveFx thank you. How would you recommend doing this? Would setting it in the JSON config file `.vscode/iisexpress.json` similar to how overriding the port number is currently done be OK?

**Comment by JustDre** [comment]
Maybe I'm missing something (because it seems too obvious) but can't we get the port number from the .csproj file?

Project/ProjectExtensions/VisualStudio/FlavorProperties/WebProjectProperties/DevelopmentServerPort

**Comment by warrenbuckley** [comment]
Yes you could @JustDre but this does not necessarily depend with a folder being opened with a .csproj file in it.

**Comment by cyberfighter89** [comment]
@warrenbuckley I would also really like this feature implemented. I think your idea of putting it in the JSON config file will work out perfectly.
Thanks. Great Plugin!

**Comment by mikiest** [comment]
I agree, I would need this enhancement.

Regarding the settings currently in iisexpress.json, a preferable approach (for me) would be to simply add plugin settings (including the port if needed) in the user/workspace settings ([API here](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesconfiguration)).

**Comment by warrenbuckley** [comment]
Hi @JoveFx @cyberfighter89 @mikiest this has now been implemented in todays release of v0.0.6

A new property in the `.vscode/iisexpress.json` file of `path` can be set to a full path of a subfolder inside your workspace/project you open in VSCode.
