### ISSUE TITLE
Not sure how to hook up to Angular live development server

### ISSUE THREAD

**Issue by brent-lemmon** [warrenbuckley/IIS-Express-Code#402]
Hello, I primarily work on ASP.NET applications with an angular front end. I began developing in Visual Studio, however I've come to much prefer VSCode. I would like to fully transition away from Visual Studio but I still use it to launch my in-development web apps hosted on IIS Express, as they will be eventually be hosted on a proper IIS server. I cannot seem to configure my project within VSCode to be able to launch with an IIS Express host even using this extension. Could anyone give me some pointers on how I can connect my angular front end with an IIS Express web server launched through this extension?

**Comment by warrenbuckley** [comment]
Hiya @brent-lemmon 
The IIS Express extension is best used when the open folder is used as the root of the application to run as the website.

In your case you may need to configure the .vscode/iisexpress.json file to set a `path` property to point to the output folder of your web application.
https://github.com/warrenbuckley/IIS-Express-Code#settings-for-iis-express

Hopefully this helps you. If not feel free to re-open this issue :)
