### ISSUE TITLE
support multiple websites in project

### ISSUE THREAD

**Issue by zmikes** [warrenbuckley/IIS-Express-Code#42]
Would it be possible to start more than one website at the same time such as the API and the front end when set up separately within the same project. Perhaps by repeating the block of settings in iisexpress.json
```
{
    "port": 44301,
    "path": "c:\\devGit\\Project\\SiteOne\\",
    "clr": "v4.0",
    "protocol": "https"
},
{
    "port": 44302,
    "path": "c:\\devGit\\Project\\SiteTwo\\",
    "clr": "v4.0",
    "protocol": "https"
}
```

**Comment by rezaGIS** [comment]
Did you ever find a solution to this ? I need something similar

**Comment by orjhor** [comment]
+1

**Comment by orjhor** [comment]
Pull request for this here: #44
