### ISSUE TITLE
How to turn on 32 bit application support

### ISSUE THREAD

**Issue by bmqy** [warrenbuckley/IIS-Express-Code#43]
How to turn on 32 bit application support, please!

**Comment by warrenbuckley** [comment]
Sorry for the very long delay in answering @bmqy 
Is this still a problem for you?

I will close this for now, but please re-open if you need to.

But in regards to how the 32bit or 64bit version of IISExpress is used is done by this piece of code using the ENV variable https://github.com/warrenbuckley/IIS-Express-Code/blob/master/src/verification.ts#L77-L82
