### ISSUE TITLE
Update usage instructions

### ISSUE THREAD

**Issue by craigs100** [warrenbuckley/IIS-Express-Code#47]
Have installed VS Code and IIS Express extension. Cannot run a web site as the current instructions appear to be missing steps. How and where do you instruct a site to start/stop, etc. What do you click on, what instructions do you enter, etc. Would be helpful for people like me who haven't seen VS Code before but looking forward to using it.

Thanks.

**Comment by gavco98uk** [comment]
Did you find an answer to this? It's far from clear what to do. Animated GIF on the page is too small to see, but appears to show a URL at the bottom of the page that is clickable? This doesnt seem to appear for me after installing the extension.

**Comment by billoreid** [comment]
Press F1 while in VS Code to bring up the command prompt. 
Type "iis" at the prompt and you should see the three IIS Express commands for starting, stopping, and restarting.

**Comment by warrenbuckley** [comment]
Thank you @billoreid for help answer this, in my absence.

@craigs100 this is a good idea/suggestion I will update the readme with some usage instructions as I just assumed everyone would know how to use this.

**Comment by TimZander** [comment]
I would like to know how to start with http and https and display both ports, but cannot find how to configure this.

**Comment by warrenbuckley** [comment]
@TimZander what are exactly are you trying to do here. Then I can try & replicate the scenario here.

**Comment by TimZander** [comment]
> 
> 
> @TimZander what are exactly are you trying to do here. Then I can try & replicate the scenario here.

I'm trying to run the site on both https and http, as it would be in Visual Studio where you configure both http and https ports for a site and IIS Express serves on both. Is that possible?

**Comment by warrenbuckley** [comment]
@TimZander I think it could be possible when I get round to looking at this PR next which supports using an applicationhost.config to launch IISExpress which is how big brother VS does it afaik

https://github.com/warrenbuckley/IIS-Express-Code/issues/38#issuecomment-653938162

**Comment by warrenbuckley** [comment]
Readme has been updated in closer prep for 1.2.0 launch
https://github.com/warrenbuckley/IIS-Express-Code
