### ISSUE TITLE
IIS Express' command for gulp task

### ISSUE THREAD

**Issue by asadsahi** [warrenbuckley/IIS-Express-Code#5]
Hi Warren, nice extension. 

Is there a command available to use e.g in gulp task or any way to run Node IIS express using a launch task in VS code?

**Comment by warrenbuckley** [comment]
Hello @asadsahi 
I am not entirely clear on what you would like to do/achieve with this.

You could just use your launch task config file to invoke the IIS Express command line tool with the params you need.

This extension is just setting the current VSCode folder/workspace and passing it to the IIS Express command line tool.
