### ISSUE TITLE
Default keybindings conflict with critical VS Code keybindings

### ISSUE THREAD

**Issue by Tyriar** [warrenbuckley/IIS-Express-Code#50]
These override run, stop debugging and restart debugging, all very important keybindings for VS Code. This is basically an automatic uninstall for me as it breaks my workflow when working with other languages.

https://github.com/warrenbuckley/IIS-Express-Code/blob/494dafaa423cfba283d91f5be28367b75c9b33d2/package.json#L54-L65

**Comment by warrenbuckley** [comment]
@Tyriar it is possible to map custom key bindings if you find this conflicting with the default ones by VSCode.

There is a workaround/solution for you where you can customise or remove the keybindings all together for my IIS Express extension if you wish to do so.
https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-editor

As this can be resolved I am closing this issue

**Comment by Tyriar** [comment]
@warrenbuckley I know it is, I'm on the VS Code team. This is just UX advice as overwriting such critical keybinding, especially without context keys leads to a bad experience.

**Comment by warrenbuckley** [comment]
@Tyriar thanks for the feedback.
What do you suggest I do here, remove the keybindings all together or...?

I used these key bindings as I come from the big brother Visual Studio and I am used to doing CTRL+F5 etc for just launching IISExpress for me.

If you have any other UX or suggestions I would love to hear them & take them on board to making a better extension for all.

**Comment by Tyriar** [comment]
For stop and restart, both of the default keybindings happen when `inDebugMode` so you can change those to this:

```json
 { 
     "command": "extension.iis-express.stop", 
     "key": "shift+f5", 
     "when": "isWindows && !inDebugMode"
 }, 
 { 
     "command": "extension.iis-express.restart", 
     "key": "ctrl+shift+f5",
     "when": "isWindows && !inDebugMode"
 } 
```

The last one is a little more nuanced as `workbench.action.debug.run` (the default ctrl+f5) works when not in debug mode as well. You could do the same thing for a quick and easy win but it wouldn't cover all cases. If you wanted to go all out here you could for example create your own context key and only use it in workspaces that you know need the IIS server. For example you could set your context key to true if there is a `web.config` (and/or other files) and only use the keybinding then. This may or may not make sense or be worth the effort as I'm not that familiar with the .NET/IIS world anymore. Regardless covering the first 2 would have solved by issues when I was experimenting with Umbrace as I use the default stop and restart all the time, not run though.

You can check out some examples of the sorts of complex keybindings you can do in the Gitlens extension: https://github.com/eamodio/vscode-gitlens/blob/6cfd9fdedd7c6ec3bfa732af7c418bbbecdfba54/package.json#L5550

**Comment by warrenbuckley** [comment]
Thanks for the feedback @Tyriar I appreciate it and nice to hear a member of the VSCode team is looking to play around with Umbraco, did you end up using it or building anything with it?

**Comment by Tyriar** [comment]
@warrenbuckley I didn't end up doing that project so no. I actually worked with Umbraco professionally like 8 years ago now and mainly wanted to see where it went 🙂
