### ISSUE TITLE
The following site was not found in the configuration file: 'xxxxx-53dfbadc-fbad-4829-969a-e855abc6e16d'

### ISSUE THREAD

**Issue by 37Stars** [warrenbuckley/IIS-Express-Code#51]
So.... which applicationhost.config file is the plugin using? I've added the necessary configuration to every config file I found (documents and Program Files (x86)) and it still doesn't find the site. It works on one computer (where I found and copied the settings) but not on another. Both are 64-bit Windows 10, same updates, same login, etc.

**Comment by ackbarapp** [comment]
I am having the same issue and was wondering if you found the solution for this?  Appreciate the help!

**Comment by emeria** [comment]
Also having this issue--trying to launch Umbraco using this extension in vs code.

**Comment by kuba-aws** [comment]
This extension has a hardcoded link to where IIS Express is installed.

Workaround - go to where IIS Express is installed (somewhere in program files), launch it manually and then this VS Code extension will work correctly.

**Comment by warrenbuckley** [comment]
Closing this as this the paths to IISExpress.exe and appcmd.exe can be configured with this PR #86
