### ISSUE TITLE
Sponsorware message keeps on coming up in IIS Express

### ISSUE THREAD

**Issue by CastellanSystems** [warrenbuckley/IIS-Express-Code#533]
Hi Warren,

I recently sponsored you but the sponsorware message keeps on coming up in IIS Express. How do I get rid of it?

Michael

**Comment by warrenbuckley** [comment]
Hello @CastellanSystems 
Sorry to hear that it still shows for you.

You need to login to your GitHub account inside VSCode, it should have prompted you.

If not from the command palette type/search for `IIS` and you should see all the IIS Express commands from the extension, including the one labelled `Login to GitHub`

If this is still problematic, let me know and I will happy to help you further.

Thanks,
Warren :)

**Comment by CastellanSystems** [comment]
Hi Warren,

I'm already logged into my GitHub account but I'm still getting the message. Is there anything I need to do once I've logged in?

Michael

**Comment by warrenbuckley** [comment]
@CastellanSystems This is very odd indeed & sorry for the delay (I moved last week so got lost in the noise & chaos there)
Can you please try to uninstall and reinstall the extension to see if that makes any difference and then we can take it from there.

After a reinstall, can you tell me if still shows up please.
My current thought is that my sponsorware logic is not working with one time sponsors (as this is a newer a GitHub sponsors feature)

**Comment by CastellanSystems** [comment]
Hi Warren,

I did as you suggested, uninstalled and reinstall. Then I proceeded to start a website multiple times to see if the sponsorware message would show up. It was looking good but on the 15th time it appeared. So it obviously is not working.

Michael

**Comment by warrenbuckley** [comment]
OK lets do some debugging with the GraphQL API from GitHub.
https://docs.github.com/en/graphql/overview/explorer

In the top left hand window use the following query (This is part of the same query I run to check if you are a sponsored user)
https://github.com/warrenbuckley/Is-Github-Sponsor

```
{
  viewer {
    login
    sponsorshipsAsSponsor(first: 100) {
      nodes {
        sponsorable {
          __typename
          ... on User {
            login
            name
          }
        }
      }
      pageInfo {
        hasNextPage
        endCursor
      }
      totalCount
    }
  }
}
```

This should return a result like this, ideally with a result with a listing to my Github username `warrenbuckley` in the nodes array
```
{
  "data": {
    "viewer": {
      "login": "warrenbuckley",
      "sponsorshipsAsSponsor": {
        "nodes": [
          {
            "sponsorable": {
              "__typename": "User",
              "login": "leekelleher",
              "name": "Lee Kelleher"
            }
          },
          {
            "sponsorable": {
              "__typename": "User",
              "login": "Shazwazza",
              "name": "Shannon Deminick"
            }
          }
        ],
        "pageInfo": {
          "hasNextPage": false,
          "endCursor": "Mg"
        },
        "totalCount": 2
      }
    }
  }
}
```

![image](https://user-images.githubusercontent.com/1389894/142841208-2303678a-ac0e-4903-b273-6969905e336a.png)

**Comment by CastellanSystems** [comment]
Hi Warren,

I ran the query and this is the output that I got:
```
{
  "data": {
    "viewer": {
      "login": "CastellanSystems",
      "sponsorshipsAsSponsor": {
        "nodes": [
          {
            "sponsorable": {
              "__typename": "User",
              "login": "warrenbuckley",
              "name": "Warren Buckley"
            }
          }
        ],
        "pageInfo": {
          "hasNextPage": false,
          "endCursor": "MQ"
        },
        "totalCount": 1
      }
    }
  }
}
```

Doesn't really lopk like what you suggested. See the image attached:

![Results](https://user-images.githubusercontent.com/88517190/142972490-2d2ee7a4-a324-431b-ac8d-3eeeb988ac69.png)

**Comment by warrenbuckley** [comment]
OK this is odd as the GraphQL query shows you correctly being a sponsor of me. I thought it may display incorrectly with you being a one time off sponsor.

Are you behind a corporate firewall or anything similar?
I am wondering if the VSCode extension can't correctly make the request to the URL to check if your an active sponsor & thus continues you to show the sponsorware message.

It should be making a HTTP POST request to `https://warren-buckley.co.uk/IsActiveSponsor` with a `token` property which is your GitHub token.

If we are still out of luck I will see if I can get an updated build that will capture some details into a logfile

**Comment by CastellanSystems** [comment]
Hi Warren,

No I'm not behind a corporate firewall but I do have a firewall. I use Norton 360 and it has a "smart" firewall. 

Michael

**Comment by CastellanSystems** [comment]
HI Warren,

I haven't got the message since I ran that test, it just may be coincidence. I'll keep watching it and let you know.

Michael

**Comment by CastellanSystems** [comment]
Spoke too early; I just got it.

**Comment by CastellanSystems** [comment]
Hi Warren,

I turned off my Norton 360 smart firewall and ran ISS Express. On the 13th time I got the sponsorware message. SO my firewall is not the issue.

Michael

**Comment by warrenbuckley** [comment]
Hi Michael,
I will need to add some further logging but don't have time right now (due to some personal stuff coming up)

Can you use a tool like Charles or Fiddler to ensure its making the request to `https://warren-buckley.co.uk/IsActiveSponsor`

https://www.charlesproxy.com
https://www.telerik.com/fiddler

**Comment by CastellanSystems** [comment]
Hi Warren,

This is beyond my technical knowledge. I did as you suggested and used Charles. The 2 images attached is the output I got. I can see an entry for https://warren-buckley.co.uk, but I can't confirm it's for IsActiveSponsor.

Hopefully you can make sense of the output.

![Charles_Output](https://user-images.githubusercontent.com/88517190/143872492-ffd16770-1a47-49c4-a566-06730830441d.png)
![Charles_Output2](https://user-images.githubusercontent.com/88517190/143872503-bf4ed023-d723-45e5-b146-42387b74cbec.png)

**Comment by warrenbuckley** [comment]
OK well good to know it's making a request out to the service to check if your an active sponsor.
I have some personal family emergency stuff come up right now, so I will get back to you when I next can.

Some last minute things I can think of are comparing versions and checking that GitHub auth is allowed for the extension

My version of VSCode is as follows, can you get me a copy of yours please from `Help --> About`
```
Version: 1.62.3 (user setup)
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:11:14.551Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044
```

https://user-images.githubusercontent.com/1389894/144208013-cc1ee7e8-73ea-4dd0-98a0-9841823f91be.mp4

**Comment by CastellanSystems** [comment]
Hi Warren,

As requested:

Version: 1.62.3 (user setup)
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:11:14.551Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

Also, see the images

![Image-1](https://user-images.githubusercontent.com/88517190/144416721-e6f9aae5-a385-41be-9f0a-34c13564680c.png)
![Image-2](https://user-images.githubusercontent.com/88517190/144416739-e984db9b-74f7-4693-bcea-700163de4e31.png)
 attached.

**Comment by warrenbuckley** [comment]
Hi @CastellanSystems 
Is that a second GitHub account logged into VSCode that you have blanked out?

I wonder if there is an issue where if multiple GitHub accounts or auth'd accounts are logged in that it sends the wrong credentials over to the API endpoint.

If you are able to test the theory for me please if only one account is logged in/authorized with VSCode then does this begin to work?

**Comment by CastellanSystems** [comment]
Hi Warren,

It's not a 2nd GitHub account; it's my personal Microsoft account; I've blanked it out because it's using my personal  home email address. I've checked and VSCode tells me that no extension is using it.

I signed out of that account and I'm only signed into 1 account. On the 6th start of IIS Express I got the Sponsorware message.

Michael

**Comment by warrenbuckley** [comment]
OK I am really started to get stumped by all of this and can apologise you keep getting it.
I will need to find some time later in the week to update the extension and the sponsor check code to add some more logs and details so we can debug it together to figure out what its happening.

Warren :)

**Comment by CastellanSystems** [comment]
Thanks Warren,

I understand; I've had issues myself like this. I look forward to hearing from you when you've been able to make those changes.

Michael.

**Comment by warrenbuckley** [comment]
OK I have pushed 1.5.0 out that contains this PR https://github.com/warrenbuckley/IIS-Express-Code/pull/546

https://github.com/warrenbuckley/IIS-Express-Code/releases/tag/v1.5.0

https://marketplace.visualstudio.com/items?itemName=warren-buckley.iis-express

![image](https://user-images.githubusercontent.com/1389894/144881187-d97f621f-32de-4624-9dba-c58e9d4f8eab.png)

**Comment by CastellanSystems** [comment]
Hi Warren,

I've installed your update and ran IIS Express until I got the sponsorware message; this it the output I got:

![image](https://user-images.githubusercontent.com/88517190/144943702-131a96a2-c349-4460-b699-6c44495bf0a9.png)


I don't use Azure so that's why I fail that test. I just develop and maintain ASP.NET websites.

Based on the image in your last message, am I supposed to have some entry in my web.config file?

Michael

**Comment by warrenbuckley** [comment]
Hi Michael
It's my badly worded log messages the code that checks your GitHub username is a valid sponsor is hosted on an Azure function and has nothing to do with your own code, but at least I know where the issue lies.

Strange considering we checked the GraphQL with GitHub earlier in this thread. I will need to add some logging to that code at https://warren-buckley.co.uk/IsActiveSposnor to see what is happening and why it fails.

**Comment by warrenbuckley** [comment]
OK this is weird indeed, so I am looking through the logs and it shows you are sponsoring 0 people on Sunday the 12th December but previously in the logs it did show up as 1 person.

![image](https://user-images.githubusercontent.com/1389894/146184153-66738b9b-7913-4d3c-906e-bcabe675a625.png)

I am not quite show how to continue debugging this issue

**Comment by CastellanSystems** [comment]
Hi Warren,

Can't you amend a setting to show I'm sponsoring you?

If you can't and can't work a way to get rid of the message for me, as I sponsored you in order to get right of the message, can you please return my money?

Michael

**Comment by warrenbuckley** [comment]
Hey Michael
I will see if I can manually update it, but I still find it weird the result is now not showing up as a sponsor. Latest guess was that is was a one time sponsor (so valid for a month) in the terms of GitHub APIs.

I will code something in manually to bypass the sponsor check and it still does not work then I think we will need to reach out to GitHub support in order to see if I can get you a refund of $10

Warren :)

**Comment by warrenbuckley** [comment]
OK so added code to the Azure Function for a list of bypassed users with your username in it.
I hope this solves the issue for you - you can see the new code in these two commits here...

https://github.com/warrenbuckley/Is-Github-Sponsor/commit/62aef17d8d4f82188fe8e04cef555036ec2776b7
https://github.com/warrenbuckley/Is-Github-Sponsor/commit/f7dfefe86f8ca245b37ff1ec64394605b6d31727

You can see it working with my username in the list of bypassed users in the logs, so I will be looking out for your username `
![image](https://user-images.githubusercontent.com/1389894/146788617-c7c54716-c861-4242-b41a-4fe330b15732.png)

**Comment by CastellanSystems** [comment]
Hi Warren,

See the attached image showing the log. It looks like if has worked.
![image](https://user-images.githubusercontent.com/88517190/146842626-beb30732-ce7a-4056-b779-eae64790ffd6.png)

I've started ISS Express 20 times and no message; in the past I would had got it already. So I consider this issue resolved.

Thanks for your efforts over the past month and a bit.

Michael
