### ISSUE TITLE
Option to specify browser

### ISSUE THREAD

**Issue by ItsPepperpot** [warrenbuckley/IIS-Express-Code#58]
Somewhat related to https://github.com/warrenbuckley/IIS-Express-Code/issues/37
It would be nice if you could specify the browser that the webpage is opened in. I use Chrome for day-to-day browsing (and it's my default browser) but Firefox Dev for web development.
Thanks for the great extension. 👍

**Comment by warrenbuckley** [comment]
This is something I would need to investigate but it does seem a good idea to implement @ItsPepperpot

**Comment by warrenbuckley** [comment]
Could use a config enum to use which command to run

```
start www.microsoft.com (Default browser)
start msedge www.microsoft.com
start firefox www.microsoft.com
start opera www.microsoft.com
start chrome www.microsoft.com
```
