### ISSUE TITLE
.vs applicationhost.config

### ISSUE THREAD

**Issue by jrood** [warrenbuckley/IIS-Express-Code#6]
Is there a way to use the applicationhost.config that is in the .vs folder?

**Comment by mogulman52** [comment]
Some thoughts on this.  The IISExpress user applicationhost.config file is at:
"C:\Users\<user>\Documents\IISExpress\config\applicationhost.config"

You modify this file for things like PHP support.  VS uses this file when running the website. When you start ISSExpress from the command line you do this:

"C:\Program Files\IIS Express\iisexpress.exe" /config:"C:\Users\<user>\Documents\IISExpress\config\applicationhost.config"

It starts the first site in the sites list and uses the port specified.  You can specify a specific site by using the /site: option.  You can override the path by adding /path: "C:\Mysites\mysite"

If you don't specify a config file ISSExpress uses the one at:
"C:\Program Files\IIS Express\AppServer\applicationhost.config"

It makes a timestamp copy and puts it at:
"C:\Users\<user>\AppData\Local\Temp\iisexpress"

Although a big No-No I was able to get PHP support by modifying this file.  I would prefer adding an option to the IISExpress.json file called config to load the proper config file.

{
   config: "C:\Users\<user>\Documents\IISExpress\config\applicationhost.config"
}

**Comment by justinlabenne** [comment]
I recently began using VSCode and did find it seriously difficult to go back to a few basic Php sites and get them up and running. I was using WebMatrix, switched to VSCode, found I could fire up complex projects easily, but couldn't run a basic site easily. As @mogulman52 did, I had to do the exact same thing. This feature utilized within your extension would be extremely valuable to me.

**Comment by steveharoz** [comment]
@mogulman52 Are you sure that's where the applicationhost.config is copied from? I've changed the one at `C:\Users\<user>\Documents\IISExpress\config\applicationhost.config` and `C:\Program Files\IIS Express\AppServer\applicationhost.config`. But when I rerun the iis, it makes a new config file in `Temp\iisexpress` that doesn't have my changes. Where the hell is that file copied from??? Is it hard coded into the exe?

**Comment by mogulman52** [comment]
I did this on a 32-bit Win 10 machine.  I'll check on my 64-bit Win 10 machine but try this one if it exists.
C:\Program Files (x86)\IIS Express\AppServer\applicationhost.config

**Comment by steveharoz** [comment]
@mogulman52 That solved it. Thanks!

**Comment by warrenbuckley** [comment]
Hi all here.
I managed to work on some new features but ran out of time for today to get around to implementing this.

@mogulman52 can you give me an example of what gets modified in the config file to support PHP for example & is the only/main reason you would ever need to modify this?

Sorry I'm a .NET WebDeveloper so have no experience with PHP

**Comment by mogulman52** [comment]
You need to add a fastCgi section.

        <fastCgi>
            <application fullPath="C:\xampp\php\php-cgi.exe" />
        </fastCgi>

In the handlers section add this:

<add name="PHP_via_FastCGI" path="*.php" verb="*" modules="FastCgiModule" scriptProcessor="C:\xampp\php\php-cgi.exe" resourceType="Unspecified" />

**Comment by mogulman52** [comment]
I only modify it for PHP support.  You can modify it to set the default website.

**Comment by warrenbuckley** [comment]
OK I am considering supporting PHP by using appcmd to add & remove sites to the default location config file at `cd %HOMEPATH%/documents/IISExpress/config`

So if you were to modify this file with your PHP support then it should work for any IISExpress sites.
The approach is to add a site using `appcmd.exe` with support for http or https bindings

I think this will be better than having a config option in the iisexpress.json config file for VSCode in my opinion.

Thoughts @mogulman52 @jrood @steveharoz @justinlabenne

**Comment by mogulman52** [comment]
appcmd is the preferred approach.  I don't use it directly very often.  If fact the only time I remember is adding PHP.  Visual Studio uses it to add default websites behind the scenes.

**Comment by warrenbuckley** [comment]
OK will look at using `appcmd` then when I get some free time again next to integrate this

**Comment by warrenbuckley** [comment]
This is coming in a 1.0.0 release shortly :)
