### ISSUE TITLE
.webp images are not supported

### ISSUE THREAD

**Issue by lou-far** [warrenbuckley/IIS-Express-Code#653]
An `img` tag with a `src` value of a .webp image fails to load. Browser Console reports 404: Not Found.

**Comment by warrenbuckley** [comment]
@lou-far this is not specific to the IIS Express VSCode plugin as I assume you have the same issue if you was to run the same folder/site with IIS Express without VSCode.


I suggest you add this to your global IIS Express server configuration to map the file extension & mime-type
https://stackoverflow.com/questions/46044933/iis-server-blocking-access-to-webp-files

Global IIS Express Config location
`%userprofile%\documents\iisexpress\config\applicationhost.config`


Alternatively, if your project is a .NET Framework project with its own web.config XML file.

```xml
<system.webServer>
  <staticContent>
    <mimeMap fileExtension=".webp" mimeType="image/webp" />
  </staticContent>
</system.webServer>
```
