### ISSUE TITLE
Blazor App not showing

### ISSUE THREAD

**Issue by Supeede** [warrenbuckley/IIS-Express-Code#684]
set up blank blazor app. start IIS Epress, error 403.14 shows up (directoryBrowsing forbidden)
enable directoryBrowsing delete the error, but IIS Express list the directory, and don't start the Blazor app.
there is no htm(l) file to browse/start, because Blazor don't need one.

so, how to use IIS Express with Blazor?

**Comment by warrenbuckley** [comment]
@Supeede I have not done any work with Blazor but knowing its a newer tech from Microsoft.
You probably want to use the dotnet CLI commands such as `dotnet build` and `dotnet run` in the terminal to get it to run.

I originally made this IIS Express extension for VSCode when I was working with a lot of .NET Framework websites and wanted a quick way to run a folder as a site.

If you still think it should be able to work with IIS Express, can you give me some notes or details to reproduce this please.

**Comment by Supeede** [comment]
@warrenbuckley Hi. Thx for reply. At the Moment there is no possible Solution for me, to get your Ext to work. 
build and run works, the app is running in net core (launch) but iis express list the directory. 
in vs works iis express well. but in code, maybe because its the lightweight VS version, the background publishing ist the same as in VS code. 
i will follow your ext and hope, in future will be a option to use.
at the moment i have to publish first, then iis express works. but thats no solution to create/debug an app.

**Comment by lextm** [comment]
Microsoft C# extension + [Blazor debug extension](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.blazorwasm-companion) are needed if you want to debug Blazor WebAssembly projects in VS Code.

Alternatively, you can use the new [IIS/IIS Express extension](https://marketplace.visualstudio.com/items?itemName=lextudio.iis).

**Comment by warrenbuckley** [comment]
Hi @lextm thanks for helping out, perhaps the Vlazor debug extension will help @Supeede 
However, it is good to have alternative VSCode extensions in the community and different options, however promoting it on issues and PRs to this repository is slightly distasteful and not in the spirit of open source IMO.
