### ISSUE TITLE
A different approach to integrate IIS Express with VS Code

### ISSUE THREAD

**Issue by lextm** [warrenbuckley/IIS-Express-Code#698]
While this extension has been out for many years, its feature set is always limited. That's understandable for a hobby project, and the complexity of IIS/IIS Express configuration system also raises the bar.

The following issues have been reported but never worked on,

| Issue | Status | Comments |
| ----- | ------- | ---------- |
| #684 | Closed as not supported | Blazor projects are supported by [new extension](https://marketplace.visualstudio.com/items?itemName=lextudio.iis) |
| #654 | Open | Can be done with [new extension](https://marketplace.visualstudio.com/items?itemName=lextudio.iis) |
| #558 | Open | Can be done with [new extension](https://marketplace.visualstudio.com/items?itemName=lextudio.iis) |
| #411 | Closed but not resolved | Can be done with [new extension](https://marketplace.visualstudio.com/items?itemName=lextudio.iis) |
| #406 | Closed as not supported | Can be done with [new extension](https://marketplace.visualstudio.com/items?itemName=lextudio.iis) |
| #402 | Closed but not resolved | Can be done with [new extension](https://marketplace.visualstudio.com/items?itemName=lextudio.iis) |
| #98 | Closed but not resolved | Might be done with [new extension](https://marketplace.visualstudio.com/items?itemName=lextudio.iis) |
| #96 | Closed | Not yet in [new extension](https://marketplace.visualstudio.com/items?itemName=lextudio.iis) |
| #60 | Closed as not supported | Not supported by [new extension](https://marketplace.visualstudio.com/items?itemName=lextudio.iis) |
| #49 | Closed but not resolved | Might be done with [new extension](https://marketplace.visualstudio.com/items?itemName=lextudio.iis) |
| #46 | Closed but not resolved | Can be done with [new extension](https://marketplace.visualstudio.com/items?itemName=lextudio.iis) || #33 | Open  |  Pull request #36 was not merged. Can be done with [new extension](https://marketplace.visualstudio.com/items?itemName=lextudio.iis) |
| #34 | Closed but not resolved | Might be done with [new extension](https://marketplace.visualstudio.com/items?itemName=lextudio.iis) |
| #31 | Open | Can be done with [new extension](https://marketplace.visualstudio.com/items?itemName=lextudio.iis)  |
| #29 | Closed but not resolved | Can be done with [new extension](https://marketplace.visualstudio.com/items?itemName=lextudio.iis) |

I created Jexus Manager to enable IIS/IIS Express using a user interface similar to IIS Manager, so with it parsing configuration files and revealing most settings is easy.

You can give the [new VS Code extension](https://marketplace.visualstudio.com/items?itemName=lextudio.iis) a try. While feature parity isn't a design goal, it is interesting to explore further on some of the items.

**Comment by warrenbuckley** [comment]
Hi @lextm thanks for commenting and giving your opinion.
However, it is good to have alternative VSCode extensions in the community and different options, however promoting it on issues and PRs to this repository is slightly distasteful and not in the spirit of open source IMO.

**Comment by graealex** [comment]
> Hi [@lextm](https://github.com/lextm) thanks for commenting and giving your opinion. However, it is good to have alternative VSCode extensions in the community and different options, however promoting it on issues and PRs to this repository is slightly distasteful and not in the spirit of open source IMO.

OR you could just fix the issues. #31 is open since 2017. That's 9 years ago and trivial HTTP stuff.
