### ISSUE TITLE
PHP Support

### ISSUE THREAD

**Issue by mogulman52** [warrenbuckley/IIS-Express-Code#8]
Is there a way to get PHP support in the server?  I have used IISExpress with Visual Studio and PHP.

**Comment by warrenbuckley** [comment]
This tool currently does not do this out of the box. It is simply invoking IISExpress from the command line for the current folder.

http://www.iis.net/learn/extensions/using-iis-express/running-iis-express-from-the-command-line

WebMatrix or Visual Studio must be adding extra files or config when it detects a project/folder is using PHP.

Doing a quick search brought this up. Seems like IISExpress needs to be configured
http://stackoverflow.com/questions/6099143/enabling-php-on-iis-express-with-visual-studio-sans-webmatrix

With the easiest way using Web Platform installer to install `PHP for IISExpress`

Another link with similar info
http://stackoverflow.com/questions/7080374/how-to-run-php-on-iis7-5-express

I am closing this for now as it seems to be environmental setup and something should be done by yourself as opposed to this VS Code Extension automatically doing it.
