### ISSUE TITLE
New issue to version 0.0.4 "No handler found for the command: 'extension.iis-express'. An extension might be missing an activation event."

### ISSUE THREAD

**Issue by JeffJacobson** [warrenbuckley/IIS-Express-Code#9]
In the command panel, select *IIS Express: Run Website*

This results in the following error:

    No handler found for the command: 'extension.iis-express'. An extension might be missing an activation event.

I only started getting this error after upgrading to the 0.0.4 version.

**Comment by warrenbuckley** [comment]
Thanks for raising this @JeffJacobson I will look when I get back to my desk in the morning to see what is happening.

**Comment by mogulman52** [comment]
It only started failing when I upgraded to VSCode 1.3 although I don't remember upgrading to 0.0.4.

**Comment by warrenbuckley** [comment]
@JeffJacobson & @mogulman52 this has now been fixed in v0.0.5

**Comment by JeffJacobson** [comment]
It works for me, now, too.  Thanks!
