### ISSUE TITLE
"The following site was not found in the configuration file..." when starting IIS Express from within VS Code

### ISSUE THREAD

**Issue by patrick-lim** [warrenbuckley/IIS-Express-Code#98]
Just as a test, I created a web application, launched VS Code, installed the Extension and fired up IIS Express. I get...

The following site was not found in the configuration file: 'test5-6cccf563-3792-40fa-a7c2-aecbbac2fd75'

In my launchsettings.json file, I have this:

{
  "iisSettings": {
    "windowsAuthentication": false, 
    "anonymousAuthentication": true, 
    "iisExpress": {
      "applicationUrl": "http://localhost:26944",
      "sslPort": 44394
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "test5": {
      "commandName": "Project",
      "launchBrowser": true,
      "applicationUrl": "https://localhost:5001;http://localhost:5000",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}

**Comment by warrenbuckley** [comment]
Hi @patrick-lim 
This is currently not supported to use the applicationhost.config file. 

It’s something I want to look into soon & was reported in this issue #33

I will close this issue as it’s a duplicate

**Comment by graealex** [comment]
That's not a duplicate - I have don't have applicationhost.config either, but launch fails with "The following site was not found in the configuration file: 'xxx-9c9bfb49-e198-4318-b49f-fd70d2ad75cb'".

**Comment by graealex** [comment]
This might be related to this post: https://stackoverflow.com/questions/52032552/umbraco-error-when-trying-to-run-iis-express-start-website-in-visual-studio
